#!/bin/sh
# Build the wheels
cd ../
mv dist/*.whl dist/legacy/
cd scripts
./build

# Update git
VERSION=$(python -c "from gnutools import __version__;print(__version__)")
rm -r $(find . -type d -iname __pycache__)
git checkout -b ${VERSION}_auto
git add .
git commit -m $VERSION
git push origin ${VERSION}_auto
